remote_theme: poole/lanyon
# theme: jekyll-theme-minimal
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
# show_downloads: true
# header_pages:
#  - index.md
#  - releasenotes.md
#  - plugin.md
